server:
  port: 8080

confirmation-channels.email:
  smtp:
    host: "<smtp_host>"
    port: "<smtp_port>"
    sender: "<email_sender>"
    username: "<smtp_username>"
    password: "<smtp_password>"
